<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue/v1/queue.proto

namespace Nitric\Proto\Queue\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response for sending a collection of tasks
 *
 * Generated from protobuf message <code>nitric.queue.v1.QueueSendBatchResponse</code>
 */
class QueueSendBatchResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of tasks that failed to be queued
     *
     * Generated from protobuf field <code>repeated .nitric.queue.v1.FailedTask failedTasks = 1;</code>
     */
    private $failedTasks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nitric\Proto\Queue\V1\FailedTask[]|\Google\Protobuf\Internal\RepeatedField $failedTasks
     *           A list of tasks that failed to be queued
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Queue\V1\Queue::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of tasks that failed to be queued
     *
     * Generated from protobuf field <code>repeated .nitric.queue.v1.FailedTask failedTasks = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFailedTasks()
    {
        return $this->failedTasks;
    }

    /**
     * A list of tasks that failed to be queued
     *
     * Generated from protobuf field <code>repeated .nitric.queue.v1.FailedTask failedTasks = 1;</code>
     * @param \Nitric\Proto\Queue\V1\FailedTask[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFailedTasks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nitric\Proto\Queue\V1\FailedTask::class);
        $this->failedTasks = $arr;

        return $this;
    }

}

