<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue/v1/queue.proto

namespace Nitric\Proto\Queue\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nitric.queue.v1.QueueReceiveResponse</code>
 */
class QueueReceiveResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Array of tasks popped off the queue
     *
     * Generated from protobuf field <code>repeated .nitric.queue.v1.NitricTask tasks = 1;</code>
     */
    private $tasks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nitric\Proto\Queue\V1\NitricTask[]|\Google\Protobuf\Internal\RepeatedField $tasks
     *           Array of tasks popped off the queue
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Queue\V1\Queue::initOnce();
        parent::__construct($data);
    }

    /**
     * Array of tasks popped off the queue
     *
     * Generated from protobuf field <code>repeated .nitric.queue.v1.NitricTask tasks = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTasks()
    {
        return $this->tasks;
    }

    /**
     * Array of tasks popped off the queue
     *
     * Generated from protobuf field <code>repeated .nitric.queue.v1.NitricTask tasks = 1;</code>
     * @param \Nitric\Proto\Queue\V1\NitricTask[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTasks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nitric\Proto\Queue\V1\NitricTask::class);
        $this->tasks = $arr;

        return $this;
    }

}

