<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document/v1/document.proto

namespace Nitric\Proto\Document\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nitric.document.v1.DocumentQueryStreamResponse</code>
 */
class DocumentQueryStreamResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The stream document
     *
     * Generated from protobuf field <code>.nitric.document.v1.Document document = 1;</code>
     */
    protected $document = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nitric\Proto\Document\V1\Document $document
     *           The stream document
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Document\V1\Document::initOnce();
        parent::__construct($data);
    }

    /**
     * The stream document
     *
     * Generated from protobuf field <code>.nitric.document.v1.Document document = 1;</code>
     * @return \Nitric\Proto\Document\V1\Document
     */
    public function getDocument()
    {
        return isset($this->document) ? $this->document : null;
    }

    public function hasDocument()
    {
        return isset($this->document);
    }

    public function clearDocument()
    {
        unset($this->document);
    }

    /**
     * The stream document
     *
     * Generated from protobuf field <code>.nitric.document.v1.Document document = 1;</code>
     * @param \Nitric\Proto\Document\V1\Document $var
     * @return $this
     */
    public function setDocument($var)
    {
        GPBUtil::checkMessage($var, \Nitric\Proto\Document\V1\Document::class);
        $this->document = $var;

        return $this;
    }

}

