<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document/v1/document.proto

namespace Nitric\Proto\Document\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Provides a query expression type
 *
 * Generated from protobuf message <code>nitric.document.v1.Expression</code>
 */
class Expression extends \Google\Protobuf\Internal\Message
{
    /**
     * The query operand or attribute
     *
     * Generated from protobuf field <code>string operand = 1;</code>
     */
    protected $operand = '';
    /**
     * The query operator [ == | < | <= | > | >= | startsWith ]
     *
     * Generated from protobuf field <code>string operator = 2;</code>
     */
    protected $operator = '';
    /**
     * The query expression value
     *
     * Generated from protobuf field <code>.nitric.document.v1.ExpressionValue value = 3;</code>
     */
    protected $value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $operand
     *           The query operand or attribute
     *     @type string $operator
     *           The query operator [ == | < | <= | > | >= | startsWith ]
     *     @type \Nitric\Proto\Document\V1\ExpressionValue $value
     *           The query expression value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Document\V1\Document::initOnce();
        parent::__construct($data);
    }

    /**
     * The query operand or attribute
     *
     * Generated from protobuf field <code>string operand = 1;</code>
     * @return string
     */
    public function getOperand()
    {
        return $this->operand;
    }

    /**
     * The query operand or attribute
     *
     * Generated from protobuf field <code>string operand = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOperand($var)
    {
        GPBUtil::checkString($var, True);
        $this->operand = $var;

        return $this;
    }

    /**
     * The query operator [ == | < | <= | > | >= | startsWith ]
     *
     * Generated from protobuf field <code>string operator = 2;</code>
     * @return string
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * The query operator [ == | < | <= | > | >= | startsWith ]
     *
     * Generated from protobuf field <code>string operator = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkString($var, True);
        $this->operator = $var;

        return $this;
    }

    /**
     * The query expression value
     *
     * Generated from protobuf field <code>.nitric.document.v1.ExpressionValue value = 3;</code>
     * @return \Nitric\Proto\Document\V1\ExpressionValue|null
     */
    public function getValue()
    {
        return $this->value;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * The query expression value
     *
     * Generated from protobuf field <code>.nitric.document.v1.ExpressionValue value = 3;</code>
     * @param \Nitric\Proto\Document\V1\ExpressionValue $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Nitric\Proto\Document\V1\ExpressionValue::class);
        $this->value = $var;

        return $this;
    }

}

