<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document/v1/document.proto

namespace Nitric\Proto\Document\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Provides a document identifying key type
 *
 * Generated from protobuf message <code>nitric.document.v1.Key</code>
 */
class Key extends \Google\Protobuf\Internal\Message
{
    /**
     * The item collection
     *
     * Generated from protobuf field <code>.nitric.document.v1.Collection collection = 1;</code>
     */
    protected $collection = null;
    /**
     * The items unique id
     *
     * Generated from protobuf field <code>string id = 2;</code>
     */
    protected $id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nitric\Proto\Document\V1\Collection $collection
     *           The item collection
     *     @type string $id
     *           The items unique id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Document\V1\Document::initOnce();
        parent::__construct($data);
    }

    /**
     * The item collection
     *
     * Generated from protobuf field <code>.nitric.document.v1.Collection collection = 1;</code>
     * @return \Nitric\Proto\Document\V1\Collection|null
     */
    public function getCollection()
    {
        return $this->collection;
    }

    public function hasCollection()
    {
        return isset($this->collection);
    }

    public function clearCollection()
    {
        unset($this->collection);
    }

    /**
     * The item collection
     *
     * Generated from protobuf field <code>.nitric.document.v1.Collection collection = 1;</code>
     * @param \Nitric\Proto\Document\V1\Collection $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkMessage($var, \Nitric\Proto\Document\V1\Collection::class);
        $this->collection = $var;

        return $this;
    }

    /**
     * The items unique id
     *
     * Generated from protobuf field <code>string id = 2;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * The items unique id
     *
     * Generated from protobuf field <code>string id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

}

