<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faas/v1/faas.proto

namespace Nitric\Proto\Faas\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Messages the client is able to send to the server
 *
 * Generated from protobuf message <code>nitric.faas.v1.ClientMessage</code>
 */
class ClientMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Client message ID, used to pair requests/responses
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    protected $content;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Client message ID, used to pair requests/responses
     *     @type \Nitric\Proto\Faas\V1\InitRequest $init_request
     *           Client initialisation request
     *     @type \Nitric\Proto\Faas\V1\TriggerResponse $trigger_response
     *           Client responsding with result of
     *           a trigger
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Faas\V1\Faas::initOnce();
        parent::__construct($data);
    }

    /**
     * Client message ID, used to pair requests/responses
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Client message ID, used to pair requests/responses
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Client initialisation request
     *
     * Generated from protobuf field <code>.nitric.faas.v1.InitRequest init_request = 2;</code>
     * @return \Nitric\Proto\Faas\V1\InitRequest|null
     */
    public function getInitRequest()
    {
        return $this->readOneof(2);
    }

    public function hasInitRequest()
    {
        return $this->hasOneof(2);
    }

    /**
     * Client initialisation request
     *
     * Generated from protobuf field <code>.nitric.faas.v1.InitRequest init_request = 2;</code>
     * @param \Nitric\Proto\Faas\V1\InitRequest $var
     * @return $this
     */
    public function setInitRequest($var)
    {
        GPBUtil::checkMessage($var, \Nitric\Proto\Faas\V1\InitRequest::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Client responsding with result of
     * a trigger
     *
     * Generated from protobuf field <code>.nitric.faas.v1.TriggerResponse trigger_response = 3;</code>
     * @return \Nitric\Proto\Faas\V1\TriggerResponse|null
     */
    public function getTriggerResponse()
    {
        return $this->readOneof(3);
    }

    public function hasTriggerResponse()
    {
        return $this->hasOneof(3);
    }

    /**
     * Client responsding with result of
     * a trigger
     *
     * Generated from protobuf field <code>.nitric.faas.v1.TriggerResponse trigger_response = 3;</code>
     * @param \Nitric\Proto\Faas\V1\TriggerResponse $var
     * @return $this
     */
    public function setTriggerResponse($var)
    {
        GPBUtil::checkMessage($var, \Nitric\Proto\Faas\V1\TriggerResponse::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->whichOneof("content");
    }

}

