<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/v1/auth.proto

namespace Nitric\Proto\Auth\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Successful create requests provide no response currently.
 *
 * Generated from protobuf message <code>nitric.auth.v1.UserCreateResponse</code>
 */
class UserCreateResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Auth\V1\Auth::initOnce();
        parent::__construct($data);
    }

}

