<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue/v1/queue.proto

namespace GPBMetadata\Queue\V1;

class Queue
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Struct::initOnce();
        $pool->internalAddGeneratedFile(
            '
ˆ	
queue/v1/queue.protonitric.queue.v1"L
QueueSendRequest
queue (	)
task (2.nitric.queue.v1.NitricTask"
QueueSendResponse"R
QueueSendBatchRequest
queue (	*
tasks (2.nitric.queue.v1.NitricTask"J
QueueSendBatchResponse0
failedTasks (2.nitric.queue.v1.FailedTask"3
QueueReceiveRequest
queue (	
depth ("B
QueueReceiveResponse*
tasks (2.nitric.queue.v1.NitricTask"7
QueueCompleteRequest
queue (	
lease_id (	"
QueueCompleteResponse"H

FailedTask)
task (2.nitric.queue.v1.NitricTask
message (	"j

NitricTask

id (	
lease_id (	
payload_type (	(
payload (2.google.protobuf.Struct2î
QueueServiceM
Send!.nitric.queue.v1.QueueSendRequest".nitric.queue.v1.QueueSendResponse\\
	SendBatch&.nitric.queue.v1.QueueSendBatchRequest\'.nitric.queue.v1.QueueSendBatchResponseV
Receive$.nitric.queue.v1.QueueReceiveRequest%.nitric.queue.v1.QueueReceiveResponseY
Complete%.nitric.queue.v1.QueueCompleteRequest&.nitric.queue.v1.QueueCompleteResponseBb
io.nitric.proto.queue.v1BQueuesPZnitric/v1;v1ªNitric.Proto.Queue.v1ÊNitric\\Proto\\Queue\\V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

