<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event/v1/event.proto

namespace Nitric\Proto\Event\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Result of publishing an event
 *
 * Generated from protobuf message <code>nitric.event.v1.EventPublishResponse</code>
 */
class EventPublishResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The id of the published message
     * When an id was not supplied
     * one should be automatically generated
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           The id of the published message
     *           When an id was not supplied
     *           one should be automatically generated
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event\V1\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * The id of the published message
     * When an id was not supplied
     * one should be automatically generated
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * The id of the published message
     * When an id was not supplied
     * one should be automatically generated
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

}

