<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event/v1/event.proto

namespace Nitric\Proto\Event\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Nitric Event Model
 *
 * Generated from protobuf message <code>nitric.event.v1.NitricEvent</code>
 */
class NitricEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * A Unique ID for the Nitric Event
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * A content hint for the events payload
     *
     * Generated from protobuf field <code>string payloadType = 2;</code>
     */
    protected $payloadType = '';
    /**
     * The payload of the event
     *
     * Generated from protobuf field <code>.google.protobuf.Struct payload = 3;</code>
     */
    protected $payload = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           A Unique ID for the Nitric Event
     *     @type string $payloadType
     *           A content hint for the events payload
     *     @type \Google\Protobuf\Struct $payload
     *           The payload of the event
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event\V1\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * A Unique ID for the Nitric Event
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * A Unique ID for the Nitric Event
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * A content hint for the events payload
     *
     * Generated from protobuf field <code>string payloadType = 2;</code>
     * @return string
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * A content hint for the events payload
     *
     * Generated from protobuf field <code>string payloadType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkString($var, True);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * The payload of the event
     *
     * Generated from protobuf field <code>.google.protobuf.Struct payload = 3;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getPayload()
    {
        return isset($this->payload) ? $this->payload : null;
    }

    public function hasPayload()
    {
        return isset($this->payload);
    }

    public function clearPayload()
    {
        unset($this->payload);
    }

    /**
     * The payload of the event
     *
     * Generated from protobuf field <code>.google.protobuf.Struct payload = 3;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->payload = $var;

        return $this;
    }

}

