<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event/v1/event.proto

namespace Nitric\Proto\Event\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Represents an event topic
 *
 * Generated from protobuf message <code>nitric.event.v1.NitricTopic</code>
 */
class NitricTopic extends \Google\Protobuf\Internal\Message
{
    /**
     * The Nitric name for the topic
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The Nitric name for the topic
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event\V1\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * The Nitric name for the topic
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The Nitric name for the topic
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

