<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event/v1/event.proto

namespace Nitric\Proto\Event\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for the Topic List method
 *
 * Generated from protobuf message <code>nitric.event.v1.TopicListRequest</code>
 */
class TopicListRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event\V1\Event::initOnce();
        parent::__construct($data);
    }

}

