<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event/v1/event.proto

namespace Nitric\Proto\Event\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Topic List Response
 *
 * Generated from protobuf message <code>nitric.event.v1.TopicListResponse</code>
 */
class TopicListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of found topics
     *
     * Generated from protobuf field <code>repeated .nitric.event.v1.NitricTopic topics = 1;</code>
     */
    private $topics;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nitric\Proto\Event\V1\NitricTopic[]|\Google\Protobuf\Internal\RepeatedField $topics
     *           The list of found topics
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Event\V1\Event::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of found topics
     *
     * Generated from protobuf field <code>repeated .nitric.event.v1.NitricTopic topics = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTopics()
    {
        return $this->topics;
    }

    /**
     * The list of found topics
     *
     * Generated from protobuf field <code>repeated .nitric.event.v1.NitricTopic topics = 1;</code>
     * @param \Nitric\Proto\Event\V1\NitricTopic[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTopics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Nitric\Proto\Event\V1\NitricTopic::class);
        $this->topics = $arr;

        return $this;
    }

}

