<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/v1/auth.proto

namespace GPBMetadata\Auth\V1;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Í
auth/v1/auth.protonitric.auth.v1"P
UserCreateRequest
tenant (	

id (	
email (	
password (	"
UserCreateResponse2W
UserO
Create!.nitric.auth.v1.UserCreateRequest".nitric.auth.v1.UserCreateResponseB^
io.nitric.proto.auth.v1BAuthsPZnitric/v1;v1ªNitric.Proto.Auth.v1ÊNitric\\Proto\\Auth\\V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

