<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv/v1/kv.proto

namespace GPBMetadata\Kv\V1;

class Kv
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Struct::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ê
kv/v1/kv.protonitric.kv.v1"5
KeyValueGetRequest

collection (	
key (	"=
KeyValueGetResponse&
value (2.google.protobuf.Struct"]
KeyValuePutRequest

collection (	
key (	&
value (2.google.protobuf.Struct"
KeyValuePutResponse"8
KeyValueDeleteRequest

collection (	
key (	"
KeyValueDeleteResponse2÷
KeyValueJ
Get .nitric.kv.v1.KeyValueGetRequest!.nitric.kv.v1.KeyValueGetResponseJ
Put .nitric.kv.v1.KeyValuePutRequest!.nitric.kv.v1.KeyValuePutResponseS
Delete#.nitric.kv.v1.KeyValueDeleteRequest$.nitric.kv.v1.KeyValueDeleteResponseBh
io.nitric.proto.kv.v1B	KeyValuesPZnitric/v1;v1ªNitric.Proto.KeyValue.v1ÊNitric\\Proto\\KeyValue\\V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

