<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage/v1/storage.proto

namespace Nitric\Proto\Storage\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to retrieve a storage item
 *
 * Generated from protobuf message <code>nitric.storage.v1.StorageReadRequest</code>
 */
class StorageReadRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Nitric name of the bucket to retrieve from
     *  this will be automatically resolved to the provider specific bucket identifier.
     *
     * Generated from protobuf field <code>string bucket_name = 1;</code>
     */
    protected $bucket_name = '';
    /**
     * Key of item to retrieve
     *
     * Generated from protobuf field <code>string key = 2;</code>
     */
    protected $key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bucket_name
     *           Nitric name of the bucket to retrieve from
     *            this will be automatically resolved to the provider specific bucket identifier.
     *     @type string $key
     *           Key of item to retrieve
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Storage\V1\Storage::initOnce();
        parent::__construct($data);
    }

    /**
     * Nitric name of the bucket to retrieve from
     *  this will be automatically resolved to the provider specific bucket identifier.
     *
     * Generated from protobuf field <code>string bucket_name = 1;</code>
     * @return string
     */
    public function getBucketName()
    {
        return $this->bucket_name;
    }

    /**
     * Nitric name of the bucket to retrieve from
     *  this will be automatically resolved to the provider specific bucket identifier.
     *
     * Generated from protobuf field <code>string bucket_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBucketName($var)
    {
        GPBUtil::checkString($var, True);
        $this->bucket_name = $var;

        return $this;
    }

    /**
     * Key of item to retrieve
     *
     * Generated from protobuf field <code>string key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Key of item to retrieve
     *
     * Generated from protobuf field <code>string key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

}

