<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv/v1/kv.proto

namespace Nitric\Proto\KeyValue\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nitric.kv.v1.KeyValuePutRequest</code>
 */
class KeyValuePutRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The collection containing the existing keyValue to be inserted or updated.
     *
     * Generated from protobuf field <code>string collection = 1;</code>
     */
    protected $collection = '';
    /**
     * The unique key of the keyValue to put
     *
     * Generated from protobuf field <code>string key = 2;</code>
     */
    protected $key = '';
    /**
     * A simple JSON object
     *
     * Generated from protobuf field <code>.google.protobuf.Struct value = 3;</code>
     */
    protected $value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection
     *           The collection containing the existing keyValue to be inserted or updated.
     *     @type string $key
     *           The unique key of the keyValue to put
     *     @type \Google\Protobuf\Struct $value
     *           A simple JSON object
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kv\V1\Kv::initOnce();
        parent::__construct($data);
    }

    /**
     * The collection containing the existing keyValue to be inserted or updated.
     *
     * Generated from protobuf field <code>string collection = 1;</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * The collection containing the existing keyValue to be inserted or updated.
     *
     * Generated from protobuf field <code>string collection = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;

        return $this;
    }

    /**
     * The unique key of the keyValue to put
     *
     * Generated from protobuf field <code>string key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * The unique key of the keyValue to put
     *
     * Generated from protobuf field <code>string key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * A simple JSON object
     *
     * Generated from protobuf field <code>.google.protobuf.Struct value = 3;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getValue()
    {
        return isset($this->value) ? $this->value : null;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * A simple JSON object
     *
     * Generated from protobuf field <code>.google.protobuf.Struct value = 3;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->value = $var;

        return $this;
    }

}

