<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv/v1/kv.proto

namespace Nitric\Proto\KeyValue\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nitric.kv.v1.KeyValueDeleteRequest</code>
 */
class KeyValueDeleteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The collection containing the existing keyValue to be deleted
     *
     * Generated from protobuf field <code>string collection = 1;</code>
     */
    protected $collection = '';
    /**
     * The unique key of the keyValue to delete
     *
     * Generated from protobuf field <code>string key = 2;</code>
     */
    protected $key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection
     *           The collection containing the existing keyValue to be deleted
     *     @type string $key
     *           The unique key of the keyValue to delete
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kv\V1\Kv::initOnce();
        parent::__construct($data);
    }

    /**
     * The collection containing the existing keyValue to be deleted
     *
     * Generated from protobuf field <code>string collection = 1;</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * The collection containing the existing keyValue to be deleted
     *
     * Generated from protobuf field <code>string collection = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCollection($var)
    {
        GPBUtil::checkString($var, True);
        $this->collection = $var;

        return $this;
    }

    /**
     * The unique key of the keyValue to delete
     *
     * Generated from protobuf field <code>string key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * The unique key of the keyValue to delete
     *
     * Generated from protobuf field <code>string key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

}

