<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv/v1/kv.proto

namespace Nitric\Proto\KeyValue\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>nitric.kv.v1.KeyValuePutResponse</code>
 */
class KeyValuePutResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kv\V1\Kv::initOnce();
        parent::__construct($data);
    }

}

