<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secret/v1/secret.proto

namespace Nitric\Proto\Secret\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to get a secret from a Secret Store
 *
 * Generated from protobuf message <code>nitric.secret.v1.SecretAccessRequest</code>
 */
class SecretAccessRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The id of the secret
     *
     * Generated from protobuf field <code>.nitric.secret.v1.SecretVersion secret_version = 1;</code>
     */
    protected $secret_version = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nitric\Proto\Secret\V1\SecretVersion $secret_version
     *           The id of the secret
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Secret\V1\Secret::initOnce();
        parent::__construct($data);
    }

    /**
     * The id of the secret
     *
     * Generated from protobuf field <code>.nitric.secret.v1.SecretVersion secret_version = 1;</code>
     * @return \Nitric\Proto\Secret\V1\SecretVersion|null
     */
    public function getSecretVersion()
    {
        return $this->secret_version;
    }

    public function hasSecretVersion()
    {
        return isset($this->secret_version);
    }

    public function clearSecretVersion()
    {
        unset($this->secret_version);
    }

    /**
     * The id of the secret
     *
     * Generated from protobuf field <code>.nitric.secret.v1.SecretVersion secret_version = 1;</code>
     * @param \Nitric\Proto\Secret\V1\SecretVersion $var
     * @return $this
     */
    public function setSecretVersion($var)
    {
        GPBUtil::checkMessage($var, \Nitric\Proto\Secret\V1\SecretVersion::class);
        $this->secret_version = $var;

        return $this;
    }

}

