<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secret/v1/secret.proto

namespace Nitric\Proto\Secret\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to put a secret to a Secret Store
 *
 * Generated from protobuf message <code>nitric.secret.v1.SecretPutRequest</code>
 */
class SecretPutRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The Secret to put to the Secret store
     *
     * Generated from protobuf field <code>.nitric.secret.v1.Secret secret = 1;</code>
     */
    protected $secret = null;
    /**
     * The value to assign to that secret
     *
     * Generated from protobuf field <code>bytes value = 2;</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Nitric\Proto\Secret\V1\Secret $secret
     *           The Secret to put to the Secret store
     *     @type string $value
     *           The value to assign to that secret
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Secret\V1\Secret::initOnce();
        parent::__construct($data);
    }

    /**
     * The Secret to put to the Secret store
     *
     * Generated from protobuf field <code>.nitric.secret.v1.Secret secret = 1;</code>
     * @return \Nitric\Proto\Secret\V1\Secret|null
     */
    public function getSecret()
    {
        return $this->secret;
    }

    public function hasSecret()
    {
        return isset($this->secret);
    }

    public function clearSecret()
    {
        unset($this->secret);
    }

    /**
     * The Secret to put to the Secret store
     *
     * Generated from protobuf field <code>.nitric.secret.v1.Secret secret = 1;</code>
     * @param \Nitric\Proto\Secret\V1\Secret $var
     * @return $this
     */
    public function setSecret($var)
    {
        GPBUtil::checkMessage($var, \Nitric\Proto\Secret\V1\Secret::class);
        $this->secret = $var;

        return $this;
    }

    /**
     * The value to assign to that secret
     *
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * The value to assign to that secret
     *
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

}

