<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage/v1/storage.proto

namespace GPBMetadata\Storage\V1;

class Storage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ç
storage/v1/storage.protonitric.storage.v1"D
StorageWriteRequest

bucketName (	
key (	
body ("
StorageWriteResponse"5
StorageReadRequest

bucketName (	
key (	"#
StorageReadResponse
body ("7
StorageDeleteRequest

bucketName (	
key (	"
StorageDeleteResponse2—
StorageU
Read%.nitric.storage.v1.StorageReadRequest&.nitric.storage.v1.StorageReadResponseX
Write&.nitric.storage.v1.StorageWriteRequest\'.nitric.storage.v1.StorageWriteResponse[
Delete\'.nitric.storage.v1.StorageDeleteRequest(.nitric.storage.v1.StorageDeleteResponseBj
io.nitric.proto.storage.v1BStoragesPZnitric/v1;v1ªNitric.Proto.Storage.v1ÊNitric\\Proto\\Storage\\V1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

