<?php

/**
 * Copyright 2021 Nitric Technologies Pty Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Nitric\Api;

use Exception;
use Google\Protobuf\Struct;
use Nitric\Proto\Event\V1\NitricEvent;
use Nitric\Proto\Event\V1\EventPublishRequest;
use Nitric\Proto\Event\V1\EventClient as GrpcClient;

/**
 * Class EventClient provides a client for the Nitric Event Service.
 *
 * @category Sdk
 * @package Nitric\Api
 * @author   Nitric <maintainers@nitric.io>
 * @license  http://www.opensource.org/licenses/mit-license.html  MIT License
 * @link     https://nitric.io
 */
class EventClient extends AbstractClient
{
    private GrpcClient $client;

    /**
     * EventClient constructor.
     *
     * @param GrpcClient|null $client the autogenerated gRPC client object. Typically only injected for mocked testing.
     */
    public function __construct(GrpcClient $client = null)
    {
        parent::__construct();
        if ($client) {
            $this->client = $client;
        } else {
            $this->client = new GrpcClient($this->hostname, $this->opts);
        }
    }

    /**
     * Publish an event/message to a topic, which can be subscribed to by other services.
     *
     * @param  string      $topicName   the name of the topic to publish to
     * @param  array       $payload     content of the message to send
     * @param  string      $payloadType fully qualified name of the event payload type,
     *                                  e.g. io.nitric.example.customer.created
     * @param  string|null $id          a unique id, used to ensure idempotent processing of events.
     *                                  Defaults to a version 4 UUID.
     * @return string the request id on successful publish
     * @throws Exception
     */
    public function publish(string $topicName, array $payload = [], string $payloadType = "", string $id = null): string
    {
        $payloadStruct = new Struct();
        try {
            $payloadStruct->mergeFromJsonString(json_encode($payload));
        } catch (Exception $e) {
            throw new Exception("Failed to serialize payload. Details: " . $e->getMessage());
        }

        $event = new NitricEvent();
        $event->setPayload($payloadStruct);
        $event->setPayloadType($payloadType);
        $event->setId($id);

        $publishRequest = new EventPublishRequest();
        $publishRequest->setTopic($topicName);
        $publishRequest->setEvent($event);

        list($reply, $status) = $this->client->Publish($publishRequest)->wait();

        $this->okOrThrow($status);
        return $id;
    }
}
