<?php

namespace Nitric\Api;

use Exception;
use Google\Protobuf\Struct;
use Nitric\Proto\Event\V1\NitricEvent;
use Nitric\Proto\Event\V1\EventPublishRequest;
use Nitric\Proto\Event\V1\EventClient as GrpcClient;

/**
 * Class AbortedException
 *
 * @category Sdk
 * @package  Api
 * @author   Nitric <maintainers@nitric.io>
 * @license  http://www.opensource.org/licenses/mit-license.html  MIT License
 * @link     https://nitric.io
 */
class EventClient extends AbstractClient
{
    private GrpcClient $client;

    /**
     * EventClient constructor.
     *
     * @param GrpcClient|null $client the autogenerated gRPC client object. Typically only injected for mocked testing.
     */
    public function __construct(GrpcClient $client = null)
    {
        parent::__construct();
        if ($client) {
            $this->client = $client;
        } else {
            $this->client = new GrpcClient($this->hostname, $this->opts);
        }
    }

    /**
     * Publish an event/message to a topic, which can be subscribed to by other services.
     *
     * @param  string      $topicName   the name of the topic to publish to
     * @param  array       $payload     content of the message to send
     * @param  string      $payloadType fully qualified name of the event payload type,
     *                                  e.g. io.nitric.example.customer.created
     * @param  string|null $id          a unique id, used to ensure idempotent processing of events.
     *                                  Defaults to a version 4 UUID.
     * @return string the request id on successful publish
     * @throws Exception
     */
    public function publish(string $topicName, array $payload = [], string $payloadType = "", string $id = null): string
    {
        $payloadStruct = new Struct();
        try {
            $payloadStruct->mergeFromJsonString(json_encode($payload));
        } catch (Exception $e) {
            throw new Exception("Failed to serialize payload. Details: " . $e->getMessage());
        }

        $event = new NitricEvent();
        $event->setPayload($payloadStruct);
        $event->setPayloadType($payloadType);
        $event->setId($id);

        $publishRequest = new EventPublishRequest();
        $publishRequest->setTopic($topicName);
        $publishRequest->setEvent($event);

        list($reply, $status) = $this->client->Publish($publishRequest)->wait();

        $this->okOrThrow($status);
        return $id;
    }
}
