<?php

/**
 * Copyright 2021 Nitric Technologies Pty Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Nitric\Api;

use Nitric\Api\Queues\QueueRef;
use Nitric\Proto\Queue\V1\QueueServiceClient;
use Nitric\ProtoUtils\Utils;

/**
 * Class Queues provides a client for the Nitric Queue Service.
 * @package Nitric\Api
 */
class Queues
{
    /**
     * @var QueueServiceClient package private, not for external use.
     */
    public QueueServiceClient $_baseQueueClient;

    /**
     * QueueClient constructor.
     *
     * @param QueueServiceClient|null $client the autogenerated gRPC client object. Typically only injected for mocked testing.
     */
    public function __construct(QueueServiceClient $client = null)
    {
        if ($client) {
            $this->_baseQueueClient = $client;
        } else {
            $connection = Utils::connection();
            $this->_baseQueueClient = new QueueServiceClient($connection['hostname'], $connection['opts']);
        }
    }

    public function queue(string $name): QueueRef
    {
        return new QueueRef($this, $name);
    }
}
