<?php

/**
 * Copyright 2021 Nitric Technologies Pty Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Nitric\Api;

use Nitric\Proto\Auth\V1\UserCreateRequest;
use Nitric\Proto\Auth\V1\UserClient as GrpcClient;

/**
 * Class UserClient provides a client for the Nitric User Service.
 * @package Nitric\Api
 */
class UserClient extends AbstractClient
{
    private GrpcClient $client;

    /**
     * UserClient constructor.
     *
     * @param GrpcClient|null $client the autogenerated gRPC client object. Typically only injected for mocked testing.
     */
    public function __construct(GrpcClient $client = null)
    {
        parent::__construct();
        if ($client) {
            $this->client = $client;
        } else {
            $this->client = new GrpcClient($this->hostname, $this->opts);
        }
    }

    public function create(string $tenant, string $userID, string $email, string $password)
    {
        $request = new UserCreateRequest();
        $request->setTenant($tenant);
        $request->setId($userID);
        $request->setEmail($email);
        $request->setPassword($password);

        list($reply, $status) = $this->client->Create($request)->wait();

        $this->okOrThrow($status);
    }
}
